/*Conceder Privilégios no Tablespace: Você precisa conceder privilégios ao usuário para que ele possa alocar espaço no tablespace USERS*/
ALTER USER EDUBOLSA QUOTA UNLIMITED ON USERS;

/*População da Tabela Instituicao (com Sequence para ID_INSTITUICAO)
Inserindo dados na tabela Instituicao com a sequence ID_INSTITUICAO*/
INSERT INTO EDUBOLSA.Instituicao (ID_INSTITUICAO, NOME, CNPJ, ENDERECO, TIPO)
VALUES (SEQ_INSTITUICAO.NEXTVAL, 'Universidade Alpha', '01234567000189', 'Rua da Educação, 100, Centro', 'Publica');

INSERT INTO EDUBOLSA.Instituicao (ID_INSTITUICAO, NOME, CNPJ, ENDERECO, TIPO)
VALUES (SEQ_INSTITUICAO.NEXTVAL, 'Faculdade Beta', '02345678000190', 'Av. Universitária, 200, Bairro Nova', 'Privada');

INSERT INTO EDUBOLSA.Instituicao (ID_INSTITUICAO, NOME, CNPJ, ENDERECO, TIPO)
VALUES (SEQ_INSTITUICAO.NEXTVAL, 'Instituto Gamma', '03456789000191', 'Rua do Conhecimento, 300, Zona Sul', 'Privada');

INSERT INTO EDUBOLSA.Instituicao (ID_INSTITUICAO, NOME, CNPJ, ENDERECO, TIPO)
VALUES (SEQ_INSTITUICAO.NEXTVAL, 'Universidade Delta', '04567890000192', 'Praça da Ciência, 400, Bairro Central', 'Publica');

INSERT INTO EDUBOLSA.Instituicao (ID_INSTITUICAO, NOME, CNPJ, ENDERECO, TIPO)
VALUES (SEQ_INSTITUICAO.NEXTVAL, 'Faculdade Epsilon', '05678901000193', 'Av. da Educação, 500, Bairro Alto', 'Privada');




/*População da Tabela Curso (com Sequence para ID_CURSO)*/

INSERT INTO EDUBOLSA.Curso (ID_CURSO, NOME, TURNO, CARGA_HORARIA, VALOR_MENSALIDADE, ID_INSTITUICAO)
VALUES (SEQ_CURSO.NEXTVAL, 'Engenharia de Software', 'Matutino', 3600, 1200.00, 1);
INSERT INTO EDUBOLSA.Curso (ID_CURSO, NOME, TURNO, CARGA_HORARIA, VALOR_MENSALIDADE, ID_INSTITUICAO)
VALUES (SEQ_CURSO.NEXTVAL, 'Medicina', 'Vespertino', 4000, 2500.00, 1);
INSERT INTO EDUBOLSA.Curso (ID_CURSO, NOME, TURNO, CARGA_HORARIA, VALOR_MENSALIDADE, ID_INSTITUICAO)
VALUES (SEQ_CURSO.NEXTVAL, 'Direito', 'Noturno', 3200, 1000.00, 2);
INSERT INTO EDUBOLSA.Curso (ID_CURSO, NOME, TURNO, CARGA_HORARIA, VALOR_MENSALIDADE, ID_INSTITUICAO)
VALUES (SEQ_CURSO.NEXTVAL, 'Arquitetura', 'Matutino', 3600, 1300.00, 2);
INSERT INTO EDUBOLSA.Curso (ID_CURSO, NOME, TURNO, CARGA_HORARIA, VALOR_MENSALIDADE, ID_INSTITUICAO)
VALUES (SEQ_CURSO.NEXTVAL, 'Enfermagem', 'Noturno', 3000, 800.00, 3);
INSERT INTO EDUBOLSA.Curso (ID_CURSO, NOME, TURNO, CARGA_HORARIA, VALOR_MENSALIDADE, ID_INSTITUICAO)
VALUES (SEQ_CURSO.NEXTVAL, 'Psicologia', 'Matutino', 3200, 1100.00, 3);
INSERT INTO EDUBOLSA.Curso (ID_CURSO, NOME, TURNO, CARGA_HORARIA, VALOR_MENSALIDADE, ID_INSTITUICAO)
VALUES (SEQ_CURSO.NEXTVAL, 'Fisioterapia', 'Vespertino', 3600, 1400.00, 4);
INSERT INTO EDUBOLSA.Curso (ID_CURSO, NOME, TURNO, CARGA_HORARIA, VALOR_MENSALIDADE, ID_INSTITUICAO)
VALUES (SEQ_CURSO.NEXTVAL, 'Ciência da Computação', 'Noturno', 3000, 900.00, 4);
INSERT INTO EDUBOLSA.Curso (ID_CURSO, NOME, TURNO, CARGA_HORARIA, VALOR_MENSALIDADE, ID_INSTITUICAO)
VALUES (SEQ_CURSO.NEXTVAL, 'Odontologia', 'Matutino', 3800, 2200.00, 5);
INSERT INTO EDUBOLSA.Curso (ID_CURSO, NOME, TURNO, CARGA_HORARIA, VALOR_MENSALIDADE, ID_INSTITUICAO)
VALUES (SEQ_CURSO.NEXTVAL, 'Administração', 'Noturno', 3000, 950.00, 5);


/*População da Tabela Aluno (com Sequence para ID_ALUNO)*/

INSERT INTO EDUBOLSA.Aluno (ID_ALUNO, NOME, CPF, DATA_NASCIMENTO, SEXO, RENDA_FAMILIAR)
VALUES (SEQ_ALUNO.NEXTVAL, 'Carlos Silva', '12345678901', TO_DATE('2000-05-15', 'YYYY-MM-DD'), 'M', 1500.00);
INSERT INTO EDUBOLSA.Aluno (ID_ALUNO, NOME, CPF, DATA_NASCIMENTO, SEXO, RENDA_FAMILIAR)
VALUES (SEQ_ALUNO.NEXTVAL, 'Ana Oliveira', '23456789012', TO_DATE('1998-08-22', 'YYYY-MM-DD'), 'F', 1800.00);
INSERT INTO EDUBOLSA.Aluno (ID_ALUNO, NOME, CPF, DATA_NASCIMENTO, SEXO, RENDA_FAMILIAR)
VALUES (SEQ_ALUNO.NEXTVAL, 'Lucas Santos', '34567890123', TO_DATE('1999-12-10', 'YYYY-MM-DD'), 'M', 2000.00);
INSERT INTO EDUBOLSA.Aluno (ID_ALUNO, NOME, CPF, DATA_NASCIMENTO, SEXO, RENDA_FAMILIAR)
VALUES (SEQ_ALUNO.NEXTVAL, 'Julia Pereira', '45678901234', TO_DATE('2001-03-05', 'YYYY-MM-DD'), 'F', 2200.00);
INSERT INTO EDUBOLSA.Aluno (ID_ALUNO, NOME, CPF, DATA_NASCIMENTO, SEXO, RENDA_FAMILIAR)
VALUES (SEQ_ALUNO.NEXTVAL, 'Marcos Lima', '56789012345', TO_DATE('2002-07-18', 'YYYY-MM-DD'), 'M', 2500.00);
INSERT INTO EDUBOLSA.Aluno (ID_ALUNO, NOME, CPF, DATA_NASCIMENTO, SEXO, RENDA_FAMILIAR)
VALUES (SEQ_ALUNO.NEXTVAL, 'Larissa Souza', '67890123456', TO_DATE('2000-11-30', 'YYYY-MM-DD'), 'F', 1300.00);
INSERT INTO EDUBOLSA.Aluno (ID_ALUNO, NOME, CPF, DATA_NASCIMENTO, SEXO, RENDA_FAMILIAR)
VALUES (SEQ_ALUNO.NEXTVAL, 'Felipe Costa', '78901234567', TO_DATE('2001-09-16', 'YYYY-MM-DD'), 'M', 1700.00);
INSERT INTO EDUBOLSA.Aluno (ID_ALUNO, NOME, CPF, DATA_NASCIMENTO, SEXO, RENDA_FAMILIAR)
VALUES (SEQ_ALUNO.NEXTVAL, 'Carla Martins', '89012345678', TO_DATE('1997-02-25', 'YYYY-MM-DD'), 'F', 2100.00);
INSERT INTO EDUBOLSA.Aluno (ID_ALUNO, NOME, CPF, DATA_NASCIMENTO, SEXO, RENDA_FAMILIAR)
VALUES (SEQ_ALUNO.NEXTVAL, 'Rafael Almeida', '90123456789', TO_DATE('1998-10-12', 'YYYY-MM-DD'), 'M', 2300.00);
INSERT INTO EDUBOLSA.Aluno (ID_ALUNO, NOME, CPF, DATA_NASCIMENTO, SEXO, RENDA_FAMILIAR)
VALUES (SEQ_ALUNO.NEXTVAL, 'Tatiane Rocha', '01234567890', TO_DATE('1999-05-03', 'YYYY-MM-DD'), 'F', 2600.00);

/*População da Tabela Bolsa (com Sequence para ID_BOLSA*/

INSERT INTO EDUBOLSA.Bolsa (ID_BOLSA, TIPO, VALOR, STATUS, ID_CURSO, ID_ALUNO)
VALUES (SEQ_BOLSA.NEXTVAL, 'Integral', 1200.00, 'Disponivel', 1, 1);
INSERT INTO EDUBOLSA.Bolsa (ID_BOLSA, TIPO, VALOR, STATUS, ID_CURSO, ID_ALUNO)
VALUES (SEQ_BOLSA.NEXTVAL, 'Integral', 2500.00, 'Concedida', 2, 2);
INSERT INTO EDUBOLSA.Bolsa (ID_BOLSA, TIPO, VALOR, STATUS, ID_CURSO, ID_ALUNO)
VALUES (SEQ_BOLSA.NEXTVAL, 'Parcial', 800.00, 'Concedida', 3, 3);
INSERT INTO EDUBOLSA.Bolsa (ID_BOLSA, TIPO, VALOR, STATUS, ID_CURSO, ID_ALUNO)
VALUES (SEQ_BOLSA.NEXTVAL, 'Integral', 1300.00, 'Concedida', 4, 4);
INSERT INTO EDUBOLSA.Bolsa (ID_BOLSA, TIPO, VALOR, STATUS, ID_CURSO, ID_ALUNO)
VALUES (SEQ_BOLSA.NEXTVAL, 'Integral', 800.00, 'Disponivel', 5, 5);
INSERT INTO EDUBOLSA.Bolsa (ID_BOLSA, TIPO, VALOR, STATUS, ID_CURSO, ID_ALUNO)
VALUES (SEQ_BOLSA.NEXTVAL, 'Parcial', 1100.00, 'Concedida', 6, 6);
INSERT INTO EDUBOLSA.Bolsa (ID_BOLSA, TIPO, VALOR, STATUS, ID_CURSO, ID_ALUNO)
VALUES (SEQ_BOLSA.NEXTVAL, 'Integral', 1400.00, 'Disponivel', 7, 7);
INSERT INTO EDUBOLSA.Bolsa (ID_BOLSA, TIPO, VALOR, STATUS, ID_CURSO, ID_ALUNO)
VALUES (SEQ_BOLSA.NEXTVAL, 'Integral', 900.00, 'Concedida', 8, 8);
INSERT INTO EDUBOLSA.Bolsa (ID_BOLSA, TIPO, VALOR, STATUS, ID_CURSO, ID_ALUNO)
VALUES (SEQ_BOLSA.NEXTVAL, 'Integral', 2200.00, 'Disponivel', 9, 9);
INSERT INTO EDUBOLSA.Bolsa (ID_BOLSA, TIPO, VALOR, STATUS, ID_CURSO, ID_ALUNO)
VALUES (SEQ_BOLSA.NEXTVAL, 'Parcial', 950.00, 'Concedida', 10, 10);


/*População da Tabela Bolsa (com Sequence para ID_SELECAO*/
INSERT INTO EDUBOLSA.SELECAO (ID_SELECAO, ID_ALUNO, NOTA_ENEM, ANO_INSCRICAO, RESULTADO, ID_BOLSA)
VALUES (SEQ_SELECAO.NEXTVAL, 1, 720.5, 2024, 'Aprovado', 1);    
INSERT INTO EDUBOLSA.SELECAO (ID_SELECAO, ID_ALUNO, NOTA_ENEM, ANO_INSCRICAO, RESULTADO, ID_BOLSA)
VALUES (SEQ_SELECAO.NEXTVAL, 2, 650.3, 2024, 'Reprovado', 2);
INSERT INTO EDUBOLSA.SELECAO (ID_SELECAO, ID_ALUNO, NOTA_ENEM, ANO_INSCRICAO, RESULTADO, ID_BOLSA)
VALUES (SEQ_SELECAO.NEXTVAL, 3, 800.0, 2023, 'Aprovado', 3);
INSERT INTO EDUBOLSA.SELECAO (ID_SELECAO, ID_ALUNO, NOTA_ENEM, ANO_INSCRICAO, RESULTADO, ID_BOLSA)
VALUES (SEQ_SELECAO.NEXTVAL, 4, 590.4, 2023, 'Reprovado', 4);
INSERT INTO EDUBOLSA.SELECAO (ID_SELECAO, ID_ALUNO, NOTA_ENEM, ANO_INSCRICAO, RESULTADO, ID_BOLSA)
VALUES (SEQ_SELECAO.NEXTVAL, 5, 710.2, 2022, 'Aprovado', 5);

					    
/*População da Tabela Bolsa (com Sequence para ID_DESEMPENHO*/					
INSERT INTO EDUBOLSA.DESEMPENHO (ID_DESEMPENHO, ID_ALUNO, ID_CURSO, SEMESTRE, NOTA_MEDIA, FREQUENCIA)
VALUES (SEQ_DESEMPENHO.NEXTVAL, 1, 1, 1, 8.5, 95.0);    
INSERT INTO EDUBOLSA.DESEMPENHO (ID_DESEMPENHO, ID_ALUNO, ID_CURSO, SEMESTRE, NOTA_MEDIA, FREQUENCIA)
VALUES (SEQ_DESEMPENHO.NEXTVAL, 2, 2, 2, 7.0, 85.0);
INSERT INTO EDUBOLSA.DESEMPENHO (ID_DESEMPENHO, ID_ALUNO, ID_CURSO, SEMESTRE, NOTA_MEDIA, FREQUENCIA)
VALUES (SEQ_DESEMPENHO.NEXTVAL, 3, 3, 1, 9.0, 98.0);    
INSERT INTO EDUBOLSA.DESEMPENHO (ID_DESEMPENHO, ID_ALUNO, ID_CURSO, SEMESTRE, NOTA_MEDIA, FREQUENCIA)
VALUES (SEQ_DESEMPENHO.NEXTVAL, 4, 4, 3, 6.5, 80.0);    
INSERT INTO EDUBOLSA.DESEMPENHO (ID_DESEMPENHO, ID_ALUNO, ID_CURSO, SEMESTRE, NOTA_MEDIA, FREQUENCIA)
VALUES (SEQ_DESEMPENHO.NEXTVAL, 5, 5, 4, 8.0, 92.0);


